[project]
name = "buckshot-lambda"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.11.0"
dependencies = ["speciesnet>=5.0.3", "setuptools>=80.9<81"]
